/**
 * Rendering and persistence for criticality profiles.
 *
 * The Markdown report, the terminal table and the `.kragg/criticality.json`
 * payload all live here because all three are the same decision — how the
 * numbers are shown to somebody — and because the JSON is a CROSS-LANGUAGE
 * CONTRACT that must be translated in exactly one place.
 *
 * ── TRUNCATION IS A HUMAN-FACING CONCERN, AND ONLY THAT ────────────────────
 * `TOP_N` bounds what a PERSON reads: the `CRITICALITY.md` tables and the
 * terminal table. It deliberately does NOT bound `writeJson`, which persists
 * the complete ranked population, because that file is the enforcement input —
 * `critical-tests`, `critical-coverage`, the test-depth gates, mutation
 * targeting and `kragg map` all read it back. Capping it once meant this
 * repo's own gates enforced on 4 of its 130 critical functions while the
 * report looked complete. Keep the cap here, at the render, or the same
 * failure returns in a new shape.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { declaredCritical, declaredReasons } from "./declared.ts";
import { criticalityFreshness, criticalityPath } from "./freshness.ts";
import {
  BETWEENNESS_THRESHOLD,
  FAN_IN_THRESHOLD,
  riskLabel,
  type FunctionProfile,
} from "./profile.ts";

export { criticalityPath } from "./freshness.ts";

/**
 * How many of the riskiest functions a RENDERED report shows.
 *
 * A reading limit, not an analysis limit: `analyze` ranks the whole graph and
 * `writeJson` persists all of it. Only `formatReport` and `formatTable` — the
 * two things a human looks at — stop here.
 */
export const TOP_N = 20;

/**
 * Format call-graph metrics as Markdown, mirroring Python's `format_report`.
 *
 * Critical functions come first because the report exists to point an agent at
 * them; the non-critical tail is context for where the boundary sits. Only the
 * first {@link TOP_N} ranked functions are rendered; the full population stays
 * in `.kragg/criticality.json` for the gates.
 */
export function formatReport(profiles: readonly FunctionProfile[]): string {
  const shown = rendered(profiles);
  const declared = shown.some((profile) => profile.declaredReason !== undefined);
  const lines: string[] = [
    "# Critical Functions",
    "",
    "> Auto-generated by `kragg criticality --write`. Do not edit by hand.",
    "",
    "Functions marked critical have high fan-in or betweenness centrality.",
    "When editing them, full types, docstrings, and tests are mandatory.",
    "",
  ];
  if (declared) {
    lines.push(
      "The `Why` column says what made each one critical: its call-graph",
      "metrics, or a reviewed `critical_functions` declaration in the policy.",
      "",
    );
  }
  const critical = shown.filter((profile) => profile.isCritical);
  const nonCritical = shown.filter((profile) => !profile.isCritical);

  if (critical.length > 0) {
    lines.push(...formatSection("Critical", critical, declared));
  }
  if (nonCritical.length > 0) {
    lines.push(...formatSection("Non-critical", nonCritical, declared));
  }
  if (shown.length === 0) {
    lines.push("No functions found.");
  }
  return `${lines.join("\n")}\n`;
}

function formatSection(
  title: string,
  profiles: readonly FunctionProfile[],
  declared: boolean,
): string[] {
  const lines: string[] = [
    `## ${title}`,
    "",
    `| Function | Fan-in | Fan-out | Centrality | Risk |${declared ? " Why |" : ""}`,
    `| --- | ---: | ---: | ---: | --- |${declared ? " --- |" : ""}`,
  ];
  for (const profile of profiles) {
    lines.push(
      `| \`${profile.name}\` | ${profile.fanIn} | ${profile.fanOut} | ` +
        `${profile.betweenness.toFixed(4)} | ${riskLabel(profile)} |` +
        `${declared ? ` ${why(profile)} |` : ""}`,
    );
  }
  lines.push("");
  return lines;
}

/**
 * What made this function critical, in one phrase.
 *
 * Rendered from the profile rather than from the thresholds: "fan-in 7,
 * betweenness 0.3000" is a fact about the function and stays true whatever
 * thresholds the caller analysed with, while "over the fan-in threshold" would
 * be a claim about a number this renderer does not have. A declared function
 * shows the REASON A HUMAN GAVE, which is the whole reason the setting exists,
 * and shows the metrics alongside it when the graph would have selected it
 * anyway — both reasons are true and a reviewer should see both.
 */
function why(profile: FunctionProfile): string {
  const metrics = `fan-in ${profile.fanIn}, betweenness ${profile.betweenness.toFixed(4)}`;
  if (profile.declaredReason === undefined) {
    return profile.isCritical ? metrics : "—";
  }
  const graphCritical = profile.fanIn >= FAN_IN_THRESHOLD ||
    profile.betweenness >= BETWEENNESS_THRESHOLD;
  const declared = `declared: ${profile.declaredReason}`;
  return graphCritical ? `${declared}; ${metrics}` : declared;
}

/**
 * The profiles a HUMAN sees: the {@link TOP_N} riskiest, plus every declared
 * one the cut would have hidden.
 *
 * A declared function is typically the LOWEST-ranked thing in the graph — that
 * is why it needed declaring — so the display limit would drop exactly the
 * rows a reviewer added on purpose, and the report would silently disagree
 * with the gates enforcing on them. Declared rows are appended in ranked
 * order, after the top slice, so the ranking still reads top-down.
 */
function rendered(profiles: readonly FunctionProfile[]): readonly FunctionProfile[] {
  const top = profiles.slice(0, TOP_N);
  const rest = profiles.slice(TOP_N).filter((profile) => profile.declaredReason !== undefined);
  return [...top, ...rest];
}

/** Write the Markdown criticality report. */
export function writeReport(
  profiles: readonly FunctionProfile[],
  outputPath: string,
): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, formatReport(profiles), "utf8");
}

/**
 * The `.kragg/criticality.json` wire format.
 *
 * SNAKE_CASE ON PURPOSE. This is the cross-language contract, not TypeScript
 * style: the Python `write_json` emits exactly these keys and the same
 * downstream gates and Claude hooks read whichever file is present. The
 * translation happens here and nowhere else, the way `engine/report.ts` does
 * it for violations.
 */
export interface CriticalityPayload {
  name: string;
  fan_in: number;
  fan_out: number;
  betweenness: number;
  is_critical: boolean;
  risk: string;
}

/**
 * One entry as READ BACK from disk: a raw record, because the file may have
 * been written by either implementation at any version.
 */
export type CriticalityRecord = Readonly<Record<string, unknown>>;

/** Serialize profiles to the shared payload shape. */
export function toPayload(
  profiles: readonly FunctionProfile[],
): CriticalityPayload[] {
  return profiles.map((profile) => ({
    name: profile.name,
    fan_in: profile.fanIn,
    fan_out: profile.fanOut,
    betweenness: round4(profile.betweenness),
    is_critical: profile.isCritical,
    risk: riskLabel(profile),
  }));
}

/**
 * Round to 4 decimals, as Python's `round(value, 4)` does in `write_json`.
 *
 * `toFixed` rounds half away from zero while Python rounds half to even, so
 * the two disagree on an exact `x.xxxx5` — a value that binary floating point
 * essentially never produces from a centrality computation. `Number(...)`
 * strips the trailing zeros so `JSON.stringify` emits `0.005`, not `0.0050`,
 * matching Python's shortest round-trip repr.
 */
function round4(value: number): number {
  return Number(value.toFixed(4));
}

/**
 * Write machine-readable criticality data for agents and hooks.
 *
 * WRITES EVERY PROFILE IT IS GIVEN. This file is not a report; it is the
 * population the criticality gates enforce over, so it carries the complete
 * ranked graph and lets each consumer apply its own `is_critical` filter.
 * Truncating it to `TOP_N` — which this did — capped enforcement at whatever
 * survived the display limit. Python still truncates here (`top_n=20` in
 * `gates/criticality.py`); the record SHAPE is identical, only the number of
 * entries differs, and `docs/spec-conformance.md` records the divergence.
 *
 * `indent: 1` and the trailing newline match Python's
 * `json.dumps(payload, indent=1) + "\n"` byte for byte, so a repo that
 * switches implementations sees no diff beyond the node names themselves.
 */
export function writeJson(
  profiles: readonly FunctionProfile[],
  outputPath: string,
): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${JSON.stringify(toPayload(profiles), null, 1)}\n`, "utf8");
}

/**
 * Read `.kragg/criticality.json`; an empty list when missing, invalid, or
 * STALE.
 *
 * Degrading to empty rather than throwing is deliberate and matches Python: a
 * consumer of this file is a gate that must still report on everything else,
 * and "no criticality data" is a legitimate state for a repo that has never
 * run the analysis. Entries are returned as raw records because they may come
 * from either implementation, at any version.
 *
 * STALENESS IS CHECKED HERE, in the one place every consumer already funnels
 * through — the three gates, the Claude hook and `kragg map` all read the file
 * by calling this. Putting the check in the check pipeline instead would have
 * left the hook and the command believing a file the gates had already
 * rejected. `freshness.ts` documents the bug this closes and why a stale file
 * takes the same path as an absent one; the cost is a few milliseconds of
 * walking and hashing the sources per call — measured at ~6 ms over this
 * repo's 214 source and test files — against the ~1 s graph rebuild it makes
 * unnecessary.
 */
export function readJson(root: string): readonly CriticalityRecord[] {
  if (criticalityFreshness(root) !== "fresh") {
    return [];
  }
  let data: unknown;
  try {
    data = JSON.parse(readFileSync(criticalityPath(root), "utf8"));
  } catch {
    return [];
  }
  if (!Array.isArray(data)) {
    return [];
  }
  const records = data.filter(
    (entry): entry is CriticalityRecord =>
      typeof entry === "object" && entry !== null && !Array.isArray(entry),
  );
  return withDeclared(records, root);
}

/**
 * Apply the policy's reviewed declarations to records read off disk.
 *
 * THE POLICY WINS AT READ TIME, and that is the point. The file is a cache
 * whose freshness stamp watches the source tree, so adding a declaration to
 * `kragg.json` — which touches no source file — would otherwise leave every
 * gate reading a sidecar written before the declaration existed, enforcing
 * nothing and saying nothing. Re-deriving the flag here means a declaration is
 * in force the moment it is written, and cannot silently disagree with the
 * config.
 *
 * ADDITIVE ONLY: a record already `is_critical: true` is untouched, and no
 * record is ever flipped to false — a declaration cannot demote what the graph
 * selected. No key is added; `is_critical` is the key that was already there.
 */
function withDeclared(
  records: readonly CriticalityRecord[],
  root: string,
): readonly CriticalityRecord[] {
  const reasons = declaredReasons(declaredCritical(root));
  if (reasons.size === 0) {
    return records;
  }
  return records.map((record) => {
    const name = record["name"];
    if (record["is_critical"] === true || typeof name !== "string" || !reasons.has(name)) {
      return record;
    }
    return { ...record, is_critical: true };
  });
}

/**
 * Render the compact text table Python's `print_table` prints.
 *
 * Column widths are copied from the Python f-string so the two tools' terminal
 * output lines up when they are compared side by side. Bounded by
 * {@link TOP_N}, like the Markdown report and for the same reason.
 */
export function formatTable(profiles: readonly FunctionProfile[]): string[] {
  const shown = rendered(profiles);
  if (shown.length === 0) {
    return ["No functions found."];
  }
  // The `Why` column appears only when something is declared. A project that
  // declares nothing sees the columns Python prints, byte for byte, which is
  // what makes the two tools' tables comparable side by side; a project that
  // declares something has asked for the extra column by asking the question
  // it answers.
  const declared = shown.some((profile) => profile.declaredReason !== undefined);
  const lines: string[] = [
    `${"Function".padEnd(55)} ${"Fan-in".padStart(8)} ${"Fan-out".padStart(8)} ` +
      `${"Centrality".padStart(12)} ${"Risk".padStart(8)}${declared ? "  Why" : ""}`,
    "-".repeat(96),
  ];
  for (const profile of shown) {
    lines.push(
      `${profile.name.padEnd(55)} ${String(profile.fanIn).padStart(8)} ` +
        `${String(profile.fanOut).padStart(8)} ` +
        `${profile.betweenness.toFixed(4).padStart(12)} ` +
        `${riskLabel(profile).padStart(8)}${declared ? `  ${why(profile)}` : ""}`,
    );
  }
  return lines;
}

/**
 * Print the compact table to stdout.
 *
 * `log` is injectable so tests can assert the rendering without capturing a
 * process stream; production callers pass nothing.
 */
export function printTable(
  profiles: readonly FunctionProfile[],
  log: (line: string) => void = defaultLog,
): void {
  for (const line of formatTable(profiles)) {
    log(line);
  }
}

function defaultLog(line: string): void {
  console.log(line);
}
