/**
 * A calibration run, as markdown tables.
 *
 * The JSON output is the record; this is the thing a human reads in
 * `docs/calibration.md`. Three tables, in the order the argument has to be
 * made: WHAT was measured (so the reader can check the sample is real), HOW
 * OFTEN each gate fired, and HOW FAR from the line the population sits — then
 * the findings themselves, which is where precision gets judged by hand.
 *
 * A gate that could not run prints its reason in the count column instead of a
 * zero. "Blocked" and "clean" must never render the same, which is the same
 * rule `GateResult` follows for `error` versus `passed`.
 */

import type { CalibrationRun, Finding, GateMeasurement, SampleMeasurement } from "./model.ts";

/** The whole run as one markdown document. */
export function renderMarkdown(run: CalibrationRun): string {
  return [
    `<!-- generated by scripts/calibrate.ts — do not edit by hand -->`,
    `Measured ${run.date} with kragg at commit ${run.kraggCommit}.`,
    "",
    "Thresholds in force:",
    "",
    ...Object.entries(run.thresholds).map(([gate, text]) => `- \`${gate}\`: ${text}`),
    "",
    "### Samples",
    "",
    ...table(
      ["Sample", "Commit", "Source paths", "Files", "Lines", "Compiler", "`// kragg: ignore`"],
      run.samples.map((sample) => [
        sample.label,
        sample.commit ?? "—",
        `\`${sample.sourcePaths.join(" ")}\` (${sample.sourcePathsFrom})`,
        String(sample.files),
        String(sample.lines),
        sample.compiler,
        String(sample.suppressions),
      ]),
    ),
    "",
    "### Violations per gate",
    "",
    ...table(
      ["Sample", "Gate", "Measured", "Unit", "Violations", "Rate"],
      run.samples.flatMap((sample) =>
        sample.gates.map((gate) => [
          sample.label,
          `\`${gate.gate}\``,
          String(gate.measured),
          gate.unit,
          gate.blocked === undefined ? String(gate.violations) : `not run`,
          gate.blocked === undefined ? percent(gate.rate) : `_${gate.blocked}_`,
        ]),
      ),
    ),
    "",
    "### Distribution of the measured population",
    "",
    ...table(
      ["Sample", "Gate", "min", "p50", "p90", "p99", "max", "Buckets"],
      run.samples.flatMap((sample) =>
        sample.gates.map((gate) => [
          sample.label,
          `\`${gate.gate}\``,
          ...summaryCells(gate),
          buckets(gate),
        ]),
      ),
    ),
    "",
    "### Findings",
    "",
    ...run.samples.flatMap((sample) => findingsFor(sample)),
  ].join("\n");
}

function summaryCells(gate: GateMeasurement): readonly string[] {
  const summary = gate.summary;
  if (summary === null) {
    return ["—", "—", "—", "—", "—"];
  }
  return [summary.min, summary.p50, summary.p90, summary.p99, summary.max].map((value) =>
    String(value),
  );
}

function buckets(gate: GateMeasurement): string {
  const entries = Object.entries(gate.buckets).filter(([, count]) => count > 0);
  if (entries.length === 0) {
    return "—";
  }
  return entries.map(([name, count]) => `${name}: ${count}`).join(", ");
}

function findingsFor(sample: SampleMeasurement): readonly string[] {
  const withFindings = sample.gates.filter((gate) => gate.findings.length > 0);
  if (withFindings.length === 0) {
    return [`**${sample.label}** — no findings from any metric gate.`, ""];
  }
  return withFindings.flatMap((gate) => [
    `**${sample.label} — \`${gate.gate}\`**` +
      (gate.findingsTruncated > 0
        ? ` (worst ${gate.findings.length} of ${gate.findings.length + gate.findingsTruncated})`
        : ""),
    "",
    ...table(
      ["Location", "Symbol", "Metric", "Value", "Budget", "× over"],
      gate.findings.map((finding) => row(finding)),
    ),
    "",
  ]);
}

function row(finding: Finding): readonly string[] {
  const at = finding.line === undefined || finding.line === 0 ? "" : `:${finding.line}`;
  return [
    `\`${finding.file}${at}\``,
    finding.symbol === "" ? "—" : `\`${finding.symbol}\``,
    finding.metric,
    String(finding.value),
    String(finding.threshold),
    Number.isFinite(finding.ratio) ? finding.ratio.toFixed(2) : "∞",
  ];
}

/**
 * A markdown table.
 *
 * Every cell is pipe-escaped here rather than at the call sites: a bucket
 * legitimately named `|| sites` would otherwise split its row into extra
 * columns, and a table that silently loses a column is worse than no table.
 */
function table(
  header: readonly string[],
  rows: readonly (readonly string[])[],
): readonly string[] {
  if (rows.length === 0) {
    return ["_(nothing measured)_"];
  }
  return [
    `| ${header.map(cell).join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((cells) => `| ${cells.map(cell).join(" | ")} |`),
  ];
}

function cell(text: string): string {
  return text.split("|").join("\\|");
}

function percent(rate: number): string {
  return `${(rate * 100).toFixed(2)}%`;
}
